const ActionTypes = {
	WATCH: 'WATCH',
	UNWATCH: 'UNWATCH',
	GO_INDEX: 'GO_INDEX',
	GO_SETTINGS: 'GO_SETTINGS',
	CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
	CHANGE_REGION: 'CHANGE_REGION',
	INFORM_LOCATION: 'INFORM_LOCATION',
	INFORM_MASTERY: 'INFORM_MASTERY'
}

export default ActionTypes